@extends('frontend.layouts.master')
@section('title', 'Về chúng tôi')
@section('Content')
<div id="PageContainer" class="is-moved-by-drawer">
			<main class="main-content" role="main">
				<section id="page-wrapper">
	<div class="wrapper">
		<div class="inner">
			<div class="grid">

				<div class="grid__item large--one-whole">
					<div class="page-head">
						<h1>Công ty TNHH sản xuất và thương mại Tuấn Nguyên</h1>
					</div>
					<div class="rte">
						<p>Cùng với sự phát triển của ngành công nghệ ô tô Công ty TNHH sản xuất và thương mại Tuấn Nguyên đã có 5 năm kinh nghiệm may thảm 4D,5D,6D và bắt đầu từ ngày 14/04/2016 Công ty chúng tôi mở rộng thêm lĩnh vực chuyển giao công nghệ cho các xưởng sản xuất mới thành lập. Trải qua hơn 5 năm thành lập,phát triền dưới sự lãnh đạo của Giám Đốc cùng những nỗ lực phấn đấu của các nhân viên,Công ty đã không ngừng phát triển trở thành doanh nghiệp uy tín,chuyên nghiệp và dần có chỗ đứng trên thị trường</p>
					<!-- Text gioi thieu -->
                    <p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">&nbsp;&nbsp;<img alt="" class="attachment-266x266 " height="237" sizes="(max-width: 266px) 100vw, 266px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/08de245476fa98a4c1eb.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/08de245476fa98a4c1eb.jpg 2420w, https://tuannguyen168.vn/wp-content/uploads/2015/11/08de245476fa98a4c1eb-180x106.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/08de245476fa98a4c1eb-229x135.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/08de245476fa98a4c1eb-768x453.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important; float: right;" width="402" />Logo Công ty TNHH sản xuất và thương mại Tuấn Nguyên</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Với slogan “ tất cả vì xế yêu của bạn “&nbsp; Công ty đã, đang cung cấp các các sản phẩm và dịch vụ ngành ô tô đa dạng</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">phục vụ khách hàng như :</p>

<ul style="padding-right: 0px; padding-left: 0px; margin: 1.5em 0px 1.571em 2.5em; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; list-style: square; color: rgb(90, 96, 105);">
	<li style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">Cung cấp thảm và nguyên vật liệu sản xuất thảm 5D,6D</li>
	<li style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">Cung cấp các máy móc sản xuất hiện đại trong ngành may thảm ô tô,lắp đặt miễn phí tại nhà</li>
	<li style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">Cung cấp toàn bộ các fom, mẫu của các hãng xe, các đời khác nhau</li>
	<li style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;">Dạy toàn bộ quy trình sản xuất thảm,chuyển giao công nghệ cho các xưởng mới thành lập</li>
</ul>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Phương châm đặt khách hàng lên hàng đầu,lấy khách hàng làm giá trị cốt lõi Công ty luôn lắng nghe,thấu hiểu ,tiếp thu những yêu cầu,nhận xét của khách hàng để phát triển công ty ngày càng vững mạnh hơn,phục vụ khách hàng chất lượng tốt nhất.</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Công ty TNHH sản xuất và thương mại Tuấn Nguyên chân thành cảm ơn quý khách hàng đã luôn ủng hộ và tin dùng sản phẩm của Công ty.</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: rgb(255, 0, 0);">&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Xem ngay nếu bạn quan tâm:&nbsp;</strong></span></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">https://www.facebook.com/nguyenlieumaytham5d/&nbsp;</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">&nbsp;<a href="https://tuannguyen168.vn/cam-ket-ve-chat-luong-va-dich-vu" style="color: rgb(201, 58, 42); margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; text-decoration-line: none; transition: all 0.25s ease 0s;">Cam kết về chất lượng dịch vụ, sản phẩm khi mua hàng</a></strong></p>

<h2 style="line-height: 1.4; margin: 0px 0px 12px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 34px; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Một vài hình ảnh về Công ty</h2>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Giấy đăng ký kinh doanh Công Ty :</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="330" sizes="(max-width: 190px) 100vw, 190px" src="https://tuannguyen168.vn/wp-content/uploads/2018/07/GI%E1%BA%A4Y-%C4%90KKD_M%E1%BA%B6T-TR%C6%AF%E1%BB%9AC.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-TRƯỚC.jpg 1640w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-TRƯỚC-180x252.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-TRƯỚC-229x321.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-TRƯỚC-768x1077.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="235" /><img alt="" class="attachment-266x266 " height="328" sizes="(max-width: 188px) 100vw, 188px" src="https://tuannguyen168.vn/wp-content/uploads/2018/07/GI%E1%BA%A4Y-%C4%90KKD_M%E1%BA%B6T-SAU.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-SAU.jpg 1633w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-SAU-180x255.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-SAU-229x324.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2018/07/GIẤY-ĐKKD_MẶT-SAU-768x1086.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="232" /></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Thảm trám cafe rối cafe</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Đến với&nbsp;<b style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">Công ty Tuấn Nguyên</b>,đội ngũ thợ lành nghề có kinh nghiệm lâu năm cùng với những thiết bị hiện đại trong ngành sản xuất thảm,đội ngũ nhân viên tư vấn nhiệt tình, năng động và am hiểu sản phẩm của chúng tôi sẽ giúp bạn lựa chọn được những sản phẩm phù hợp nhất.</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Ngoài sản xuất thảm 5D,6D,Công ty còn chuyên<strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">&nbsp;cung cấp nguyên vật liệu sản xuất thảm,cung cấp máy thiết bị hiện đại</strong>&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">và chuyển giao công nghệ sản xuất thảm cho xưởng mới mở&nbsp;…</strong>&nbsp;Sản phẩm luôn được kiểm tra chất lượng kỹ lưỡng để gửi tới khách hàng.</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">Sự hài lòng của khách hàng về sản phẩm, dịch vụ là bước tiến giúp Công ty phát triển mạnh hơn. Do đó, với mục tiêu đặt lợi ích và sự uy tín của người sử dụng lên hàng đầu, đưa tới tay người tiêu dùng những sản phẩm&nbsp;<strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">hàng tốt nhất – giá hợp lý nhất&nbsp;</strong>&nbsp;chúng tôi tin rằng sẽ mang lại niềm tin vững chắc, đáp ứng sự kỳ vọng của quý khách hàng.</p>

<h2 style="line-height: 1.4; margin: 0px 0px 12px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 34px; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105);">1 vài hình ảnh xưởng sản xuất thảm 5D,6D</h2>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="483" sizes="(max-width: 200px) 100vw, 200px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/df032e9afc30126e4b21.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/df032e9afc30126e4b21.jpg 1920w, https://tuannguyen168.vn/wp-content/uploads/2015/11/df032e9afc30126e4b21-180x240.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/df032e9afc30126e4b21-229x305.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/df032e9afc30126e4b21-768x1024.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="363" /></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;">Cắt thảm để may khâu đầu tiên</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="317" sizes="(max-width: 266px) 100vw, 266px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/72926538b79259cc0083.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/72926538b79259cc0083.jpg 2560w, https://tuannguyen168.vn/wp-content/uploads/2015/11/72926538b79259cc0083-180x135.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/72926538b79259cc0083-229x172.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/72926538b79259cc0083-768x576.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="422" /></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;">May thảm 5D,6D</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="356" sizes="(max-width: 266px) 100vw, 266px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2503.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2503.jpg 959w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2503-180x135.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2503-229x172.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2503-768x576.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="475" /></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;">Hoàn thiện sản phẩm thảm 6D</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="466" sizes="(max-width: 264px) 100vw, 264px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/29342287_106085190234268_5738173652889763840_n.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/29342287_106085190234268_5738173652889763840_n.jpg 954w, https://tuannguyen168.vn/wp-content/uploads/2015/11/29342287_106085190234268_5738173652889763840_n-180x181.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/29342287_106085190234268_5738173652889763840_n-229x230.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/29342287_106085190234268_5738173652889763840_n-768x773.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="462" /></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;">Sản phẩm có nhiều kích thước,mẫu để quý khách lựa chọn</p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><strong style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: rgb(255, 0, 0);">Công ty TNHH sản xuất và thương mại Tuấn Nguyên nhận giao hàng khắp 63 tỉnh thành của nước ta&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></strong></p>

<p style="margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: &quot;Times New Roman&quot;, Times, serif; vertical-align: baseline; color: rgb(90, 96, 105); text-align: center;"><img alt="" class="attachment-266x266 " height="353" sizes="(max-width: 266px) 100vw, 266px" src="https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2544.jpg" srcset="https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2544.jpg 960w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2544-180x135.jpg 180w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2544-229x172.jpg 229w, https://tuannguyen168.vn/wp-content/uploads/2015/11/IMG_2544-768x575.jpg 768w" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; max-width: 100%; height: auto !important;" width="471" /></p>

                    <!-- end text gioi thieu -->
                    </div>

				</div>

			</div>
		</div>
	</div>
</section>

			</main>
		</div>
@endsection